#server:
#  port: 8888

#上传文件大小配置，设置为-1为无限制
#spring:
#  servlet:
#    multipart:
#      max-file-size: 300MB
#      max-request-size: 300MB
spring:
  profiles:
    active: dev

#  profiles:
#    active: dev

#  profiles:
#    active: prod

#  profiles:
#    active: test


